### ISSUE TITLE
set env vars like ANSIBLE_STDOUT_CALLBACK so that we have valid json returned

### ISSUE THREAD

**Issue by neidiom** [pgeraghty/ansible-wrapper-ruby#8]
How to set env vars like this?

````
ANSIBLE_LOAD_CALLBACK_PLUGINS=true ANSIBLE_STDOUT_CALLBACK=json ansible localhost -m setup
````
is something like this supported?

````
Ansible.config.env['ANSIBLE_STDOUT_CALLBACK'] = 'json'
````

**Comment by pgeraghty** [comment]
Try the following:
`Ansible.configure { |config| config.env['ANSIBLE_STDOUT_CALLBACK'] = 'json' }`

...and please report back if it works. I've not touched this project in some time!

**Comment by neidiom** [comment]
does not work

````
    Ansible.configure { |config|
      config.env['ANSIBLE_LOAD_CALLBACK_PLUGINS'] = true
      config.env['ANSIBLE_STDOUT_CALLBACK'] = 'json'
    }
````

**Comment by pgeraghty** [comment]
I've taken a look to figure out what I was up to with the configuration. My approach was attempting to reproduce the handy global configuration I'd seen in other libraries (for ease of use); this does have its drawbacks and in the project from which this module was extracted, I actually used an approach similar to HTTParty (and frankly it was better, I must dig up that code sometime).

However, ad hoc commands are separately configurable from playbook executions and I have not set up the global `Ansible` config to override them.

So, to configure environment variables for ad hoc commands use:
```
Ansible::AdHoc.configure { |config|
  config.env['ANSIBLE_LOAD_CALLBACK_PLUGINS'] = true
  config.env['ANSIBLE_STDOUT_CALLBACK'] = 'json'
}
```

For playbook executions, replace `AdHoc` above with `Playbook`.

Please note that this gem does have some opinionated defaults applied to both - you can see these via `Ansible.config.env`. You can also enable command echoing for debug purposes via the configuration block by adding the line:
```
config.params[:debug] = true
```

I hope that helps and I'm sorry for the slow response; I've been working mostly with Elixir for the last few years.

**Comment by neidiom** [comment]
I tested this. It works as expected. Thank you.
